### ISSUE TITLE
Question about used scripts ?

### ISSUE THREAD

**Issue by bahaa-ka** [bahaa-ka/proco-web-page#2] opened 2019-10-25 16:13 UTC
for what exactly you think you need these 2 scripts ? 
https://github.com/bahaa-ka/proco-web-page/blob/0771600161b191413f9b60eec4283ea58dba03f1/index.html#L15-L16

**Comment by WaledAlaser** [comment] 2019-10-27 11:54
i used first script for solve the problem in internet explorer 
the problem is that browser cant show some tags from html 5 
example : nav footer article ..etc 
the second script i used it for prblem in internet explorer with media query in bootstrap 
i didn't use media query now but i used this script for the future when i use media query

**Comment by bahaa-kallas** [comment] 2019-10-27 12:11
i think we can get rid of these 2 scripts. because we are not targeting Internet Explorer and you don't have to take care about it (its just  an unnecessary pain in the neck)
the main target browser is Google Chrome and in second place is Mozilla Firefox 
so if you tested on both of them only it would be great.even if there was a deference between the tow that requires from you more tweaking effort you can ignore it (and i don't think you will face a big trouble with these 2 browsers but i mentioned this just to keep in mind)
i will close the issue now because there is no point of keeping it open
feel free to reopen the issue if you have further info to provide

**Closed as completed** 2019-10-27 12:12 UTC
Labels: question
